language: r
sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libudunits2-dev

before_install:
  - sudo add-apt-repository ppa:marutter/rrutter -y
  - sudo apt-get update
  - sudo apt-get install jags

env:
 global:
   - CRAN: http://cran.rstudio.com
   - WARNINGS_ARE_ERRORS=1
   - R_BUILD_ARGS=--no-manual
   - R_CHECK_ARGS=--no-manual --as-cran

r_packages:
  - jagsUI
  - progress
  - ggplot2
  - stringr
  - grDevices
  - rgdal
  - sp
